package app.formkit.core.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// One accent (deep indigo); everything else is a near-neutral grey with a faint indigo cast.
// Dynamic colour is deliberately not used, so the app looks the same on every phone.

internal val LightColors = lightColorScheme(
    primary = Color(0xFF3F3CBB),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFE3E1FF),
    onPrimaryContainer = Color(0xFF14105E),
    inversePrimary = Color(0xFFBFBDFF),
    secondary = Color(0xFF5C5D72),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE2E0F9),
    onSecondaryContainer = Color(0xFF191A2C),
    tertiary = Color(0xFF5C5D72),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFE2E0F9),
    onTertiaryContainer = Color(0xFF191A2C),
    background = Color(0xFFFBFBFE),
    onBackground = Color(0xFF1B1B21),
    surface = Color(0xFFFBFBFE),
    onSurface = Color(0xFF1B1B21),
    surfaceVariant = Color(0xFFE4E1EC),
    onSurfaceVariant = Color(0xFF47464F),
    surfaceTint = Color(0xFF3F3CBB),
    inverseSurface = Color(0xFF303036),
    inverseOnSurface = Color(0xFFF3F0F7),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    outline = Color(0xFF787680),
    outlineVariant = Color(0xFFC8C5D0),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFBFBFE),
    surfaceDim = Color(0xFFDBD9E0),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF5F4FA),
    surfaceContainer = Color(0xFFEFEEF4),
    surfaceContainerHigh = Color(0xFFE9E8EF),
    surfaceContainerHighest = Color(0xFFE3E2E9),
)

internal val DarkColors = darkColorScheme(
    primary = Color(0xFFBFBDFF),
    onPrimary = Color(0xFF1D1880),
    primaryContainer = Color(0xFF34309E),
    onPrimaryContainer = Color(0xFFE3E1FF),
    inversePrimary = Color(0xFF3F3CBB),
    secondary = Color(0xFFC6C4DD),
    onSecondary = Color(0xFF2E2F42),
    secondaryContainer = Color(0xFF444559),
    onSecondaryContainer = Color(0xFFE2E0F9),
    tertiary = Color(0xFFC6C4DD),
    onTertiary = Color(0xFF2E2F42),
    tertiaryContainer = Color(0xFF444559),
    onTertiaryContainer = Color(0xFFE2E0F9),
    background = Color(0xFF121318),
    onBackground = Color(0xFFE4E1E9),
    surface = Color(0xFF121318),
    onSurface = Color(0xFFE4E1E9),
    surfaceVariant = Color(0xFF47464F),
    onSurfaceVariant = Color(0xFFC8C5D0),
    surfaceTint = Color(0xFFBFBDFF),
    inverseSurface = Color(0xFFE4E1E9),
    inverseOnSurface = Color(0xFF303036),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF918F9A),
    outlineVariant = Color(0xFF47464F),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF38393F),
    surfaceDim = Color(0xFF121318),
    surfaceContainerLowest = Color(0xFF0D0E13),
    surfaceContainerLow = Color(0xFF1B1B21),
    surfaceContainer = Color(0xFF1F1F25),
    surfaceContainerHigh = Color(0xFF292A2F),
    surfaceContainerHighest = Color(0xFF34343A),
)
